test:
    stage: test

    image: coopcycle/coopcycle-web-test:latest

    # Select what we should cache between builds
    cache:
      paths:
      - vendor/

    before_script:

      # Configure JSON Web Token
      - mkdir -p var/jwt
      - openssl genrsa -out var/jwt/private.pem 4096
      - openssl rsa -pubout -in var/jwt/private.pem -out var/jwt/public.pem

      # Install composer dependencies
      - composer install --prefer-dist --no-progress --no-suggest

      # Install PHP app
      - cp app/config/parameters.yml.gitlab app/config/parameters.yml
      - php bin/console doctrine:schema:create --env=test
      - cp phpunit.xml.dist phpunit.xml


    # Bring in any services we need http://docs.gitlab.com/ee/ci/docker/using_docker_images.html#what-is-a-service
    # See http://docs.gitlab.com/ce/ci/services/README.html for examples.
    services:
      - name: mdillon/postgis:9.4-alpine
        alias: postgres
      - redis:alpine
      - osrm/osrm-backend:v5.16.0
      - stripemock/stripe-mock:latest

    # Set any variables we need
    variables:
        POSTGRES_DB: coopcycle_test
        STRIPE_MOCK_API_BASE: http://localhost:12111
        SYMFONY_ENV: test

    script:
      - phpunit
      - php vendor/bin/behat -f progress
