imports:
    - { resource: config.yml }

parameters:
  assets_base_urls: [ "http://localhost:8080" ]

framework:
    router:
        resource: "%kernel.root_dir%/config/routing_dev.yml"
        strict_requirements: true
    profiler: { only_exceptions: false }
    session:
        save_path:   "/tmp"
    assets:
        base_urls: "%assets_base_urls%"

web_profiler:
    toolbar: true
    intercept_redirects: false

monolog:
    handlers:
        main:
            type: rotating_file
            path: "%kernel.logs_dir%/%kernel.environment%.log"
            level: debug
            max_files: 3
            channels: ["!event", "!api"]
        console:
            type:   console
            channels: ["!event", "!doctrine"]
        api:
            type: rotating_file
            path: "%kernel.logs_dir%/api.%kernel.environment%.log"
            level: info
            formatter: AppBundle\Monolog\Formatter\ApiFormatter
            max_files: 3
            channels: [api]
        mailer:
            level:    debug
            type:     stream
            path:     '%kernel.logs_dir%/mailer.%kernel.environment%.log'
            channels: [mailer]
        # uncomment to get logging in your browser
        # you may have to allow bigger header sizes in your Web server configuration
        #firephp:
        #    type:   firephp
        #    level:  info
        #chromephp:
        #    type:   chromephp
        #    level:  info

services:
    apns_php.logger:
        class: AppBundle\Utils\ApnsPHPLogger
        arguments: [ '@logger' ]
    apns_php.push:
        class: \ApnsPHP_Push
        arguments:
            - 1
            - "%apns_certificate_file%"
        calls:
            - method: setLogger
              arguments:
                  - '@apns_php.logger'

# Uncomment to send emails in dev
#fos_user:
#   registration:
#       confirmation:
#           enabled: true
