imports:
    - { resource: config_dev.yml }

# Use a parameter to completely overwrite framework.assets.base_urls
parameters:
  assets_base_urls: [ "%env(string:ASSETS_BASE_URL)%" ]

framework:
    test: ~
    session:
        storage_id: session.storage.mock_file
    profiler:
        collect: false
    assets:
        base_urls: "%assets_base_urls%"

doctrine:
    dbal:
        dbname:   "%database_name%_test"

web_profiler:
    toolbar: false
    intercept_redirects: false

swiftmailer:
    disable_delivery: true

snc_redis:
    clients:
        default:
            type: predis
            alias: default
            dsn: redis://%redis_host%:6379/1
            options:
                prefix: "%database_name%_test:"

m6_statsd:
    servers: {}
    clients: {}

services:
    AppBundle\EventListener\CarbonListener:
        arguments:
            - '@snc_redis.default'
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }
