api:
    resource: '.'
    type:     'api_platform'
    prefix:   '/api'

api_login_check:
    path: /api/login_check

gesdinet_jwt_refresh_token:
    path:     /api/token/refresh
    defaults: { _controller: gesdinet.jwtrefreshtoken:refresh }

app:
    resource: '@AppBundle/Action/'
    type:     'annotation'
    prefix:   '/api'

web:
    resource: '@AppBundle/Controller/'
    type:     'annotation'

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

admin_delivery_pick:
    path:     /admin/deliveries/{id}/pick
    defaults: { _controller: AppBundle:Admin:pickDelivery }
    methods:  [ POST ]

admin_delivery_deliver:
    path:     /admin/deliveries/{id}/deliver
    defaults: { _controller: AppBundle:Admin:deliverDelivery }
    methods:  [ POST ]

admin_order_invoice:
    path:     /admin/orders/{id}.pdf
    defaults: { _controller: AppBundle:Admin:orderInvoice }
    requirements: { id: '\d+' }
    methods:  [ GET ]

admin_orders:
    path:     /admin/orders
    defaults:
        _controller: AppBundle:Admin:orderList
        layout: AppBundle::admin.html.twig
        template: AppBundle:Admin:orders.html.twig
        routes:
            restaurant: admin_restaurant
            order_invoice: admin_order_invoice
    methods:  [ GET ]

admin_restaurant_new:
    path: /admin/restaurants/new
    defaults:
        _controller: AppBundle:Admin:newRestaurant
        layout: AppBundle::admin.html.twig
        template: AppBundle:Restaurant:form.html.twig
        routes:
            success: admin_restaurant
            restaurants: admin_restaurants
            menu: admin_restaurant_menu
            dashboard: admin_restaurant_dashboard
            planning: admin_restaurant_planning
    methods: [ GET, POST ]

admin_restaurant:
    path: /admin/restaurants/{id}
    defaults:
        _controller: AppBundle:Admin:restaurant
        layout: AppBundle::admin.html.twig
        template: AppBundle:Restaurant:form.html.twig
        routes:
            success: admin_restaurant
            restaurants: admin_restaurants
            menu: admin_restaurant_menu
            dashboard: admin_restaurant_dashboard
            planning: admin_restaurant_planning
    methods: [ GET, POST ]

admin_restaurants:
    path: /admin/restaurants
    defaults:
        _controller: AppBundle:Admin:restaurantList
        layout: AppBundle::admin.html.twig
        template: AppBundle:Admin:restaurants.html.twig
        routes:
            dashboard: admin_restaurant_dashboard
            menu: admin_restaurant_menu
            restaurant: admin_restaurant
    methods: [ GET ]

admin_restaurant_menu:
    path: /admin/restaurants/{id}/menu
    defaults:
        _controller: AppBundle:Admin:restaurantMenu
        layout: AppBundle::admin.html.twig
        template: AppBundle:Restaurant:form-menu.html.twig
        routes:
            success: admin_restaurant_menu
            restaurants: admin_restaurants
            restaurant: admin_restaurant
            add_section: admin_restaurant_menu_add_section
    methods: [ GET, POST ]

admin_restaurant_menu_add_section:
    path: /admin/restaurants/{id}/menu/sections
    defaults:
        _controller: AppBundle:Admin:restaurantMenu
        layout: AppBundle::admin.html.twig
        template: AppBundle:Restaurant:form-menu.html.twig
        routes:
            success: admin_restaurant_menu
            restaurants: admin_restaurants
            restaurant: admin_restaurant
            add_section: admin_restaurant_menu_add_section
        add_menu_section: true
    methods: [ POST ]

admin_restaurant_planning:
    path: /admin/restaurants/{id}/planning
    defaults:
        _controller: AppBundle:Admin:restaurantPlanning
        layout: AppBundle::admin.html.twig
        template: AppBundle:Restaurant:planning.html.twig
        routes:
            restaurants: admin_restaurants
            restaurant: admin_restaurant
    methods: [ GET, POST ]

admin_restaurant_dashboard:
    path: /admin/restaurants/{restaurantId}/dashboard
    defaults:
        _controller: AppBundle:Admin:restaurantDashboard
        layout: AppBundle::admin.html.twig
        template: AppBundle:Restaurant:dashboard.html.twig
        routes:
            restaurants: admin_restaurants
            restaurant: admin_restaurant
            dashboard: admin_restaurant_dashboard
            dashboard_order: admin_restaurant_dashboard_order
            order_accept: admin_restaurant_dashboard_order_accept
            order_refuse: admin_restaurant_dashboard_order_refuse
            order_cancel: admin_restaurant_dashboard_order_cancel
            order_ready: admin_restaurant_dashboard_order_ready
            user_details: user
    methods: [ GET ]

admin_restaurant_dashboard_order:
    path: /admin/restaurants/{restaurantId}/dashboard/{orderId}
    defaults:
        _controller: AppBundle:Admin:restaurantDashboardOrder
        layout: AppBundle::admin.html.twig
        template: AppBundle:Restaurant:dashboard.html.twig
        routes:
            restaurants: admin_restaurants
            restaurant: admin_restaurant
            dashboard: admin_restaurant_dashboard
            dashboard_order: admin_restaurant_dashboard_order
            order_accept: admin_restaurant_dashboard_order_accept
            order_refuse: admin_restaurant_dashboard_order_refuse
            order_cancel: admin_restaurant_dashboard_order_cancel
            order_ready: admin_restaurant_dashboard_order_ready
            user_details: user
    methods: [ GET ]

admin_restaurant_dashboard_order_accept:
    path: /admin/restaurants/{restaurantId}/dashboard/{orderId}/accept
    defaults:
        _controller: AppBundle:Admin:acceptOrder
        redirect_route: admin_restaurant_dashboard_order
    methods: [ POST ]

admin_restaurant_dashboard_order_refuse:
    path: /admin/restaurants/{restaurantId}/dashboard/{orderId}/refuse
    defaults:
        _controller: AppBundle:Admin:refuseOrder
        redirect_route: admin_restaurant_dashboard_order
    methods: [ POST ]

admin_restaurant_dashboard_order_ready:
    path: /admin/restaurants/{restaurantId}/dashboard/{orderId}/ready
    defaults:
        _controller: AppBundle:Admin:readyOrder
        redirect_route: admin_restaurant_dashboard_order
    methods: [ POST ]

admin_restaurant_dashboard_order_cancel:
    path: /admin/restaurants/{restaurantId}/dashboard/{orderId}/cancel
    defaults:
        _controller: AppBundle:Admin:cancelOrderFromDashboard
        redirect_route: admin_restaurant_dashboard_order
    methods: [ POST ]

admin_orders_order_cancel:
    path: /admin/orders/{id}/cancel
    defaults:
        _controller: AppBundle:Admin:cancelOrder
        redirect_route: admin_orders
    methods: [ POST ]

# Profile

profile_order_invoice:
    path:     /profile/orders/{id}.pdf
    defaults: { _controller: AppBundle:Profile:orderInvoice }
    requirements: { id: '\d+' }
    methods:  [ GET ]

profile_order:
    path:     /profile/orders/{id}
    defaults: { _controller: AppBundle:Profile:order }
    methods:  [ GET ]

profile_orders:
    path:     /profile/orders
    defaults:
        _controller: AppBundle:Profile:orderList
        layout: AppBundle::profile.html.twig
        template: AppBundle:Profile:orders.html.twig
        routes:
            restaurant: restaurant
            order_invoice: profile_order_invoice
    methods:  [ GET ]

profile_restaurant_new:
    path: /profile/restaurants/new
    defaults:
        _controller: AppBundle:Profile:newRestaurant
        layout: AppBundle::profile.html.twig
        template: AppBundle:Restaurant:form.html.twig
        routes:
            success: profile_restaurant
            restaurants: profile_restaurants
            menu: profile_restaurant_menu
            dashboard: profile_restaurant_dashboard
            planning: profile_restaurant_planning
    methods: [ GET, POST ]

profile_restaurant:
    path: /profile/restaurants/{id}
    defaults:
        _controller: AppBundle:Profile:restaurant
        layout: AppBundle::profile.html.twig
        template: AppBundle:Restaurant:form.html.twig
        routes:
            success: profile_restaurant
            restaurants: profile_restaurants
            menu: profile_restaurant_menu
            dashboard: profile_restaurant_dashboard
            planning: profile_restaurant_planning
    methods: [ GET, POST ]

profile_restaurants:
    path: /profile/restaurants
    defaults:
        _controller: AppBundle:Profile:restaurantList
        layout: AppBundle::profile.html.twig
        template: AppBundle:Profile:restaurants.html.twig
        routes:
            dashboard: profile_restaurant_dashboard
            menu: profile_restaurant_menu
            restaurant: profile_restaurant
    methods: [ GET ]

profile_restaurant_dashboard:
    path: /profile/restaurants/{restaurantId}/dashboard
    defaults:
        _controller: AppBundle:Profile:restaurantDashboard
        layout: AppBundle::profile.html.twig
        template: AppBundle:Restaurant:dashboard.html.twig
        routes:
            restaurants: profile_restaurants
            restaurant: profile_restaurant
            dashboard: profile_restaurant_dashboard
            dashboard_order: profile_restaurant_dashboard_order
            order_accept: profile_restaurant_dashboard_order_accept
            order_refuse: profile_restaurant_dashboard_order_refuse
            order_cancel: profile_restaurant_dashboard_order_cancel
            order_ready: profile_restaurant_dashboard_order_ready
            user_details: user
    methods: [ GET ]

profile_restaurant_dashboard_order:
    path: /profile/restaurants/{restaurantId}/dashboard/{orderId}
    defaults:
        _controller: AppBundle:Profile:restaurantDashboardOrder
        layout: AppBundle::profile.html.twig
        template: AppBundle:Restaurant:dashboard.html.twig
        routes:
            restaurants: profile_restaurants
            restaurant: profile_restaurant
            dashboard: profile_restaurant_dashboard
            dashboard_order: profile_restaurant_dashboard_order
            order_accept: profile_restaurant_dashboard_order_accept
            order_refuse: profile_restaurant_dashboard_order_refuse
            order_cancel: profile_restaurant_dashboard_order_cancel
            order_ready: profile_restaurant_dashboard_order_ready
            user_details: user
    methods: [ GET ]

profile_restaurant_dashboard_order_accept:
    path: /profile/restaurants/{restaurantId}/dashboard/{orderId}/accept
    defaults:
        _controller: AppBundle:Profile:acceptOrder
        redirect_route: profile_restaurant_dashboard_order
    methods: [ POST ]

profile_restaurant_dashboard_order_refuse:
    path: /profile/restaurants/{restaurantId}/dashboard/{orderId}/refuse
    defaults:
        _controller: AppBundle:Profile:refuseOrder
        redirect_route: profile_restaurant_dashboard_order
    methods: [ POST ]

profile_restaurant_dashboard_order_ready:
    path: /profile/restaurants/{restaurantId}/dashboard/{orderId}/ready
    defaults:
        _controller: AppBundle:Profile:readyOrder
        redirect_route: profile_restaurant_dashboard_order
    methods: [ POST ]

profile_restaurant_dashboard_order_cancel:
    path: /profile/restaurants/{restaurantId}/dashboard/{orderId}/cancel
    defaults:
        _controller: AppBundle:Profile:cancelOrderFromDashboard
        redirect_route: profile_restaurant_dashboard_order
    methods: [ POST ]

profile_restaurant_menu:
    path: /profile/restaurants/{id}/menu
    defaults:
        _controller: AppBundle:Profile:restaurantMenu
        layout: AppBundle::profile.html.twig
        template: AppBundle:Restaurant:form-menu.html.twig
        routes:
            success: profile_restaurant_menu
            restaurants: profile_restaurants
            restaurant: profile_restaurant
            add_section: profile_restaurant_menu_add_section
    methods: [ GET ]

profile_restaurant_menu_add_section:
    path: /profile/restaurants/{id}/menu
    defaults:
        _controller: AppBundle:Profile:restaurantMenu
        layout: AppBundle::profile.html.twig
        template: AppBundle:Restaurant:form-menu.html.twig
        routes:
            success: profile_restaurant_menu
            restaurants: profile_restaurants
            restaurant: profile_restaurant
            add_section: profile_restaurant_menu_add_section
        add_menu_section: true
    methods: [ POST ]

profile_restaurant_planning:
    path: /profile/restaurants/{id}/planning
    defaults:
        _controller: AppBundle:Profile:restaurantPlanning
        layout: AppBundle::profile.html.twig
        template: AppBundle:Restaurant:planning.html.twig
        routes:
            restaurants: profile_restaurants
            restaurant: profile_restaurant
    methods: [ GET, POST ]

profile_delivery_pick:
    path:     /profile/deliveries/{id}/pick
    defaults: { _controller: AppBundle:Profile:pickDelivery }
    methods:  [ POST ]

profile_delivery_deliver:
    path:     /profile/deliveries/{id}/deliver
    defaults: { _controller: AppBundle:Profile:deliverDelivery }
    methods:  [ POST ]

redirect_to_locale:
    path: /
    defaults:
        _controller: FrameworkBundle:Redirect:urlRedirect
        path: /%locale%
        permanent: false
