api:
    resource: '.'
    type:     'api_platform'
    prefix:   '/api'

api_login_check:
    path: /api/login_check

gesdinet_jwt_refresh_token:
    path:     /api/token/refresh
    defaults: { _controller: gesdinet.jwtrefreshtoken:refresh }

app:
    resource: '@AppBundle/Action/'
    type:     'annotation'
    prefix:   '/api'

web:
    resource: '@AppBundle/Controller/'
    type:     'annotation'

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

admin_delivery_pick:
    path:     /admin/deliveries/{id}/pick
    defaults: { _controller: AppBundle:Admin:pickDelivery }
    methods:  [ POST ]

admin_delivery_deliver:
    path:     /admin/deliveries/{id}/deliver
    defaults: { _controller: AppBundle:Admin:deliverDelivery }
    methods:  [ POST ]

profile_delivery_pick:
    path:     /profile/deliveries/{id}/pick
    defaults: { _controller: AppBundle:Profile:pickDelivery }
    methods:  [ POST ]

profile_delivery_deliver:
    path:     /profile/deliveries/{id}/deliver
    defaults: { _controller: AppBundle:Profile:deliverDelivery }
    methods:  [ POST ]

redirect_to_locale:
    path: /
    defaults:
        _controller: FrameworkBundle:Redirect:urlRedirect
        path: /%locale%
        permanent: false
