api:
    resource: '.'
    type:     'api_platform'
    prefix:   '/api'

api_login_check:
    path: /api/login_check

gesdinet_jwt_refresh_token:
    path:     /api/token/refresh
    defaults: { _controller: gesdinet.jwtrefreshtoken:refresh }

app:
    resource: '@AppBundle/Action/'
    type:     'annotation'
    prefix:   '/api'

web:
    resource: '@AppBundle/Controller/'
    type:     'annotation'

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

coopcycle_admin:
    resource: '@AppBundle/Resources/config/routing/admin.yml'

coopcycle_profile:
    resource: '@AppBundle/Resources/config/routing/profile.yml'

redirect_to_locale:
    path: /
    defaults:
        _controller: FrameworkBundle:Redirect:urlRedirect
        path: /%locale%
        permanent: false
