admin_deliveries_new:
  path: /admin/deliveries/new
  defaults:
      _controller: AppBundle:Admin:newDelivery
      layout: '@App/admin.html.twig'
      routes:
          success: admin_deliveries
          calculate_price: admin_deliveries_calculate_price
  methods:  [ GET, POST ]

admin_deliveries_calculate_price:
    path:     /admin/deliveries/calculate-price
    defaults: { _controller: AppBundle:Admin:calculateDeliveryPrice }

admin_delivery:
  path: /admin/deliveries/{id}
  defaults:
      _controller: AppBundle:Admin:editDelivery
      layout: '@App/admin.html.twig'
      routes:
          success: admin_deliveries
          calculate_price: admin_deliveries_calculate_price
  methods:  [ GET, POST ]

admin_order_new:
    path:     /admin/orders/new
    defaults: { _controller: AppBundle:Admin:newOrder }
    methods:  [ GET, POST ]

admin_order_invoice:
    path:     /admin/orders/CPCCL-{number}.pdf
    defaults: { _controller: AppBundle:Admin:orderInvoice }
    methods:  [ GET ]

admin_foodtech_dashboard:
    path:     /admin/foodtech/dashboard/{date}
    requirements:
      date: '[0-9]{4}-[0-9]{2}-[0-9]{2}|__DATE__'
    defaults:
        _controller: AppBundle:Admin:foodtechDashboard
        layout: '@App/admin.html.twig'
        template: '@App/admin/orders.html.twig'
        routes:
            restaurant: admin_restaurant
            order_invoice: admin_order_invoice
            order: admin_order
    methods:  [ GET ]

admin_order:
    path:     /admin/orders/{id}
    defaults: { _controller: AppBundle:Admin:order }
    methods:  [ GET, POST ]

admin_orders:
    path:     /admin/orders
    defaults:
        _controller: AppBundle:Admin:orderList
        layout: '@App/admin.html.twig'
        template: '@App/admin/orders.html.twig'
        routes:
            restaurant: admin_restaurant
            order_invoice: admin_order_invoice
            order: admin_order
    methods:  [ GET, POST ]

admin_restaurant_new:
    path: /admin/restaurants/new
    defaults:
        _controller: AppBundle:Admin:newRestaurant
        layout: '@App/admin.html.twig'
        template: '@App/restaurant/form.html.twig'
        routes:
            success: admin_restaurant
            restaurants: admin_restaurants
            menu_taxons: admin_restaurant_menu_taxons
            menu_taxon: admin_restaurant_menu_taxon
            products: admin_restaurant_products
            product_options: admin_restaurant_product_options
            dashboard: admin_restaurant_dashboard
            planning: admin_restaurant_planning
    methods: [ GET, POST ]

admin_restaurant:
    path: /admin/restaurants/{id}
    defaults:
        _controller: AppBundle:Admin:restaurant
        layout: '@App/admin.html.twig'
        template: '@App/restaurant/form.html.twig'
        routes:
            success: admin_restaurant
            restaurants: admin_restaurants
            menu_taxons: admin_restaurant_menu_taxons
            menu_taxon: admin_restaurant_menu_taxon
            products: admin_restaurant_products
            product_options: admin_restaurant_product_options
            dashboard: admin_restaurant_dashboard
            planning: admin_restaurant_planning
    methods: [ GET, POST ]

admin_restaurants:
    path: /admin/restaurants
    defaults:
        _controller: AppBundle:Admin:restaurantList
        layout: '@App/admin.html.twig'
        template: '@App/admin/restaurants.html.twig'
        routes:
            dashboard: admin_restaurant_dashboard
            menu_taxon: admin_restaurant_menu_taxon
            menu_taxons: admin_restaurant_menu_taxons
            restaurant: admin_restaurant
    methods: [ GET ]

admin_restaurant_menu_taxons:
    path: /admin/restaurants/{id}/menus
    defaults:
        _controller: AppBundle:Admin:restaurantMenuTaxons
        layout: '@App/admin.html.twig'
        template: '@App/restaurant/menu_taxons.html.twig'
        routes:
            restaurants: admin_restaurants
            restaurant: admin_restaurant
            menu: admin_restaurant_menu_taxon
            menu_activate: admin_restaurant_menu_taxon_activate
            new_menu: admin_restaurant_new_menu_taxon
    methods: [ GET ]

admin_restaurant_new_menu_taxon:
    path: /admin/restaurants/{id}/menus/new
    defaults:
        _controller: AppBundle:Admin:newRestaurantMenuTaxon
        layout: '@App/admin.html.twig'
        template: '@App/restaurant/menu_taxon.html.twig'
        routes:
            restaurants: admin_restaurants
            restaurant: admin_restaurant
            menu_taxons: admin_restaurant_menu_taxons
            menu_taxon: admin_restaurant_menu_taxon
            success: admin_restaurant_menu_taxons
    methods: [ GET, POST ]

admin_restaurant_menu_taxon:
    path: /admin/restaurants/{restaurantId}/menus/{menuId}
    defaults:
        _controller: AppBundle:Admin:restaurantMenuTaxon
        layout: '@App/admin.html.twig'
        template: '@App/restaurant/menu_taxon.html.twig'
        routes:
            restaurants: admin_restaurants
            restaurant: admin_restaurant
            menu_taxons: admin_restaurant_menu_taxons
            products: admin_restaurant_products
            delete_section: admin_delete_restaurant_menu_taxon_child
            success: admin_restaurant_menu_taxons
    methods: [ GET, POST ]

admin_restaurant_menu_taxon_activate:
    path: /admin/restaurants/{restaurantId}/menus/{menuId}/activate
    defaults:
        _controller: AppBundle:Admin:activateRestaurantMenuTaxon
        layout: '@App/admin.html.twig'
        routes:
            menu_taxons: admin_restaurant_menu_taxons
    methods: [ POST ]

admin_delete_restaurant_menu_taxon_child:
    path: /admin/restaurants/{restaurantId}/menus/{menuId}/sections/{sectionId}/delete
    defaults:
        _controller: AppBundle:Admin:deleteRestaurantMenuTaxonChild
        layout: '@App/admin.html.twig'
        routes:
            menu_taxon: admin_restaurant_menu_taxon
    methods: [ POST ]

admin_restaurant_products:
    path: /admin/restaurants/{id}/products
    defaults:
        _controller: AppBundle:Admin:restaurantProducts
        layout: '@App/admin.html.twig'
        template: '@App/restaurant/products.html.twig'
        routes:
            restaurants: admin_restaurants
            restaurant: admin_restaurant
            product: admin_restaurant_product
            new_product: admin_restaurant_product_new
    methods: [ GET ]

admin_restaurant_product_new:
    path: /admin/restaurants/{id}/products/new
    defaults:
        _controller: AppBundle:Admin:newRestaurantProduct
        layout: '@App/admin.html.twig'
        template: '@App/restaurant/product.html.twig'
        routes:
            restaurants: admin_restaurants
            restaurant: admin_restaurant
            products: admin_restaurant_products

admin_restaurant_product:
    path: /admin/restaurants/{restaurantId}/products/{productId}
    defaults:
        _controller: AppBundle:Admin:restaurantProduct
        layout: '@App/admin.html.twig'
        template: '@App/restaurant/product.html.twig'
        routes:
            restaurants: admin_restaurants
            restaurant: admin_restaurant
            products: admin_restaurant_products

admin_restaurant_planning:
    path: /admin/restaurants/{id}/planning
    defaults:
        _controller: AppBundle:Admin:restaurantPlanning
        layout: '@App/admin.html.twig'
        template: '@App/restaurant/planning.html.twig'
        routes:
            restaurants: admin_restaurants
            restaurant: admin_restaurant
            success: admin_restaurant_planning
    methods: [ GET, POST ]

admin_restaurant_product_options:
    path: /admin/restaurants/{id}/product-options
    defaults:
        _controller: AppBundle:Admin:restaurantProductOptions
        layout: '@App/admin.html.twig'
        template: '@App/restaurant/product_options.html.twig'
        routes:
            restaurants: admin_restaurants
            restaurant: admin_restaurant
            product_option: admin_restaurant_product_option
            new_product_option: admin_restaurant_product_option_new
    methods: [ GET ]

admin_restaurant_product_option_new:
    path: /admin/restaurants/{id}/product-options/new
    defaults:
        _controller: AppBundle:Admin:newRestaurantProductOption
        layout: '@App/admin.html.twig'
        template: '@App/restaurant/product_option.html.twig'
        routes:
            restaurants: admin_restaurants
            restaurant: admin_restaurant
            product_options: admin_restaurant_product_options
    methods: [ GET, POST ]

admin_restaurant_product_option:
    path: /admin/restaurants/{restaurantId}/product-options/{optionId}
    defaults:
        _controller: AppBundle:Admin:restaurantProductOption
        layout: '@App/admin.html.twig'
        template: '@App/restaurant/product_option.html.twig'
        routes:
            restaurants: admin_restaurants
            restaurant: admin_restaurant
            product_options: admin_restaurant_product_options
    methods: [ GET, POST ]

admin_restaurant_dashboard:
    path: /admin/restaurants/{restaurantId}/dashboard
    defaults:
        _controller: AppBundle:Admin:restaurantDashboard
        layout: '@App/admin.html.twig'
        template: '@App/restaurant/dashboard.html.twig'
        routes:
            restaurants: admin_restaurants
            restaurant: admin_restaurant
            dashboard: admin_restaurant_dashboard
            dashboard_order: admin_restaurant_dashboard_order
            order_accept: admin_restaurant_dashboard_order_accept
            order_refuse: admin_restaurant_dashboard_order_refuse
            order_cancel: admin_restaurant_dashboard_order_cancel
            order_ready: admin_restaurant_dashboard_order_ready
            order_delay: admin_restaurant_dashboard_order_delay
            user_details: user
    methods: [ GET ]

admin_restaurant_dashboard_order:
    path: /admin/restaurants/{restaurantId}/dashboard/{orderId}
    defaults:
        _controller: AppBundle:Admin:restaurantDashboardOrder
        layout: '@App/admin.html.twig'
        template: '@App/restaurant/dashboard.html.twig'
        routes:
            restaurants: admin_restaurants
            restaurant: admin_restaurant
            dashboard: admin_restaurant_dashboard
            dashboard_order: admin_restaurant_dashboard_order
            order_accept: admin_restaurant_dashboard_order_accept
            order_refuse: admin_restaurant_dashboard_order_refuse
            order_cancel: admin_restaurant_dashboard_order_cancel
            order_ready: admin_restaurant_dashboard_order_ready
            order_delay: admin_restaurant_dashboard_order_delay
            user_details: user
    methods: [ GET ]

admin_restaurant_dashboard_order_accept:
    path: /admin/restaurants/{restaurantId}/dashboard/{orderId}/accept
    defaults:
        _controller: AppBundle:Admin:acceptRestaurantOrder
        redirect_route: admin_restaurant_dashboard_order
    methods: [ POST ]

admin_order_accept:
    path: /admin/orders/{id}/accept
    defaults:
        _controller: AppBundle:Admin:acceptOrder
    methods: [ POST ]

admin_restaurant_dashboard_order_refuse:
    path: /admin/restaurants/{restaurantId}/dashboard/{orderId}/refuse
    defaults:
        _controller: AppBundle:Admin:refuseRestaurantOrder
        redirect_route: admin_restaurant_dashboard_order
    methods: [ POST ]

admin_order_refuse:
    path: /admin/orders/{id}/refuse
    defaults:
        _controller: AppBundle:Admin:refuseOrder
        redirect_route: admin_restaurant_dashboard_order
    methods: [ POST ]

admin_restaurant_dashboard_order_ready:
    path: /admin/restaurants/{restaurantId}/dashboard/{orderId}/ready
    defaults:
        _controller: AppBundle:Admin:readyOrder
        redirect_route: admin_restaurant_dashboard_order
    methods: [ POST ]

admin_restaurant_dashboard_order_delay:
    path: /admin/restaurants/{restaurantId}/dashboard/{orderId}/delay
    defaults:
        _controller: AppBundle:Admin:delayRestaurantOrder
        redirect_route: admin_restaurant_dashboard_order
    methods: [ POST ]

admin_order_delay:
    path: /admin/orders/{id}/delay
    defaults:
        _controller: AppBundle:Admin:delayOrder
    methods: [ POST ]

admin_restaurant_dashboard_order_cancel:
    path: /admin/restaurants/{restaurantId}/dashboard/{orderId}/cancel
    defaults:
        _controller: AppBundle:Admin:cancelOrderFromDashboard
        redirect_route: admin_restaurant_dashboard_order
    methods: [ POST ]

admin_restaurant_stripe_oauth_redirect:
    path: /admin/restaurants/{id}/stripe-oauth-redirect
    defaults:
        _controller: AppBundle:Admin:stripeOAuthRedirect
        redirect_after: admin_restaurant
    methods: [ GET ]

# TODO Deprecate
admin_orders_order_cancel:
    path: /admin/orders/{id}/cancel
    defaults:
        _controller: AppBundle:Admin:cancelOrder
        redirect_route: admin_orders
    methods: [ POST ]

admin_order_cancel:
    path: /admin/orders/{id}/cancel
    defaults:
        _controller: AppBundle:Admin:cancelOrder
        redirect_route: admin_orders
    methods: [ POST ]

admin_stores:
    path: /admin/stores
    defaults:
        _controller: AppBundle:Admin:storeList
        layout: '@App/admin.html.twig'
        template: '@App/admin/stores.html.twig'
        routes:
            store: admin_store
            store_delivery: admin_store_delivery
    methods:  [ GET ]

admin_store_new:
    path: /admin/stores/new
    defaults:
        _controller: AppBundle:Admin:newStore
        layout: '@App/admin.html.twig'
        routes:
            stores: admin_stores
            store_delivery: admin_store_delivery
            store_api_keys: admin_store_api_keys
    methods:  [ GET, POST ]

admin_store:
    path: /admin/stores/{id}
    defaults:
        _controller: AppBundle:Admin:store
        layout: '@App/admin.html.twig'
        routes:
            stores: admin_stores
            store_delivery: admin_store_delivery
            store_api_keys: admin_store_api_keys
    methods:  [ GET, POST ]

admin_store_delivery:
    path: /admin/stores/{id}/deliveries/new
    defaults:
        _controller: AppBundle:Admin:newStoreDelivery
        layout: '@App/admin.html.twig'
        routes:
            stores: admin_stores
            store: admin_store
            success: admin_orders
            calculate_price: admin_deliveries_calculate_price
    methods:  [ GET, POST ]

admin_store_api_keys:
    path: /admin/stores/{id}/api-keys
    defaults:
        _controller: AppBundle:Admin:apiKeys
        layout: '@App/admin.html.twig'
        routes:
            stores: admin_stores
            success: admin_store_api_keys
    methods:  [ GET, POST ]

admin_store_users:
    path: /admin/stores/{id}/users
    defaults:
        _controller: AppBundle:Admin:storeUsers
        layout: '@App/admin.html.twig'
        routes:
            stores: admin_stores
            store: admin_store
    methods:  [ GET, POST ]

admin_tag_new:
    path: /admin/settings/tags/new
    defaults:
        _controller: AppBundle:Tag:newTag
        template: '@App/admin/tag.html.twig'
        redirect_route: admin_tags

admin_tag:
    path: /admin/settings/tags/{slug}
    defaults:
        _controller: AppBundle:Tag:tag
        template: '@App/admin/tag.html.twig'
        redirect_route: admin_tags
