help:
    path: /{_locale}/help
    defaults:
        _controller: AppBundle:Help:index
    requirements:
        _locale: "%locale_regex%"
    methods:  [ GET ]

help_admin_roles:
    path: /{_locale}/help/admin/roles
    defaults:
        _controller: AppBundle:Help:renderMarkdown
        template: admin/roles/index
        title: Roles
    requirements:
        _locale: "%locale_regex%"
    methods:  [ GET ]

help_admin_zones:
    path: /{_locale}/help/admin/zones
    defaults:
        _controller: AppBundle:Help:renderMarkdown
        template: admin/zones/index
        title: Zones
    requirements:
        _locale: "%locale_regex%"
    methods:  [ GET ]
