help:
    path: /{_locale}/help
    defaults:
        _controller: AppBundle:Help:index
    requirements:
        _locale: "%locale_regex%"
    methods:  [ GET ]

help_admin_roles:
    path: /{_locale}/help/admin/roles
    defaults:
        _controller: AppBundle:Help:renderMarkdown
        template: admin/roles/index
        title: Roles
    requirements:
        _locale: "%locale_regex%"
    methods:  [ GET ]

help_admin_pricing:
    path: /{_locale}/help/admin/pricing
    defaults:
        _controller: AppBundle:Help:renderMarkdown
        template: admin/pricing/index
        title: Pricing
    requirements:
        _locale: "%locale_regex%"
    methods:  [ GET ]

help_admin_zones:
    path: /{_locale}/help/admin/zones
    defaults:
        _controller: AppBundle:Help:renderMarkdown
        template: admin/zones/index
        title: Zones
    requirements:
        _locale: "%locale_regex%"
    methods:  [ GET ]

help_admin_stores:
    path: /{_locale}/help/admin/stores
    defaults:
        _controller: AppBundle:Help:renderMarkdown
        template: admin/stores/index
        title: Stores
    requirements:
        _locale: "%locale_regex%"
    methods:  [ GET ]

help_admin_smartphone_apps:
    path: /{_locale}/help/admin/apps
    defaults:
        _controller: AppBundle:Help:renderMarkdown
        template: admin/SmartphoneApps/index
        title: Smartphone Applications
    requirements:
        _locale: "%locale_regex%"
    methods:  [ GET ]

help_admin_tasks:
    path: /{_locale}/help/admin/tasks
    defaults:
        _controller: AppBundle:Help:renderMarkdown
        template: admin/tasks/index
        title: Tasks
    requirements:
        _locale: "%locale_regex%"
    methods:  [ GET ]

help_admin_tasks_import:
    path: /{_locale}/help/admin/tasks/import
    defaults:
        _controller: AppBundle:Help:renderMarkdown
        template: admin/tasks/import
        title: Import tasks
        nav: false
    requirements:
        _locale: "%locale_regex%"
    methods:  [ GET ]
