AppBundle\Entity\Contract:
    type: entity
    table: contract
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: IDENTITY
    fields:
        minimumCartAmount:
            type: float
            column: minimum_cart_amount
        flatDeliveryPrice:
            type: float
            column: flat_delivery_price
        feeRate:
            type: float
            column: fee_rate
    oneToOne:
        restaurant:
            targetEntity: AppBundle\Entity\Restaurant
            cascade:
                - persist
            fetch: LAZY
            mappedBy: null
            inversedBy: contract
            joinColumns:
                restaurant_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
