AppBundle\Entity\Contract:
    type: entity
    table: contract
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: IDENTITY
    fields:
        minimumCartAmount:
            type: integer
            column: minimum_cart_amount
        flatDeliveryPrice:
            type: integer
            column: flat_delivery_price
        variableDeliveryPriceEnabled:
            type: boolean
            column: variable_delivery_price_enabled
        variableCustomerAmountEnabled:
            type: boolean
            column: variable_customer_amount_enabled
        feeRate:
            type: float
            column: fee_rate
        restaurantPaysStripeFee:
            type: boolean
            column: restaurant_pays_stripe
            nullable: false
            options:
                default: true
        customerAmount:
            type: integer
            column: customer_amount
            options:
                default: 0
    oneToOne:
        restaurant:
            targetEntity: AppBundle\Entity\Restaurant
            cascade:
                - persist
            fetch: LAZY
            mappedBy: null
            inversedBy: contract
            joinColumns:
                restaurant_id:
                    referencedColumnName: id
            orphanRemoval: false
    manyToOne:
        variableDeliveryPrice:
            targetEntity: AppBundle\Entity\Delivery\PricingRuleSet
            joinColumn:
                variable_delivery_price_id:
                    referencedColumnName: id
                    nullable: true
        variableCustomerAmount:
            targetEntity: AppBundle\Entity\Delivery\PricingRuleSet
            joinColumn:
                variable_customer_amount_id:
                    referencedColumnName: id
                    nullable: true
    lifecycleCallbacks: {  }
