AppBundle\Entity\DeliveryOrder:
    type: entity
    table: delivery_order
    id:
        order:
            associationKey: true
        user:
            associationKey: true
    manyToOne:
        order:
            targetEntity: Sylius\Component\Order\Model\Order
            fetch: LAZY
            mappedBy: null
            joinColumns:
                order_id:
                    referencedColumnName: id
            orphanRemoval: false
        user:
            targetEntity: AppBundle\Entity\ApiUser
            fetch: LAZY
            mappedBy: null
            joinColumns:
                user_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
