AppBundle\Entity\Delivery:
    type: entity
    table: delivery
    repositoryClass: AppBundle\Entity\DeliveryRepository
    fields:
        status:
            type: string
            nullable: true
        date:
            type: datetime
            nullable: true
        price:
            type: float
            nullable: true
        weight:
            type: integer
            nullable: true
        vehicle:
            type: string
            nullable: true
        totalExcludingTax:
            type: float
            column: total_excluding_tax
            nullable: true
        totalTax:
            type: float
            column: total_tax
            nullable: true
        totalIncludingTax:
            type: float
            column: total_including_tax
            nullable: true
    manyToOne:
        originAddress:
            targetEntity: AppBundle\Entity\Address
            cascade:
                - persist
            fetch: LAZY
            joinColumns:
                origin_address_id:
                    referencedColumnName: id
        deliveryAddress:
            targetEntity: AppBundle\Entity\Address
            cascade:
                - persist
            fetch: LAZY
            joinColumns:
                delivery_address_id:
                    referencedColumnName: id
        taxCategory:
            targetEntity: Sylius\Component\Taxation\Model\TaxCategoryInterface
            fetch: LAZY
            joinColumns:
                tax_category_id:
                    referencedColumnName: id
                    nullable: true
    oneToOne:
        order:
            targetEntity: AppBundle\Entity\Order
            fetch: LAZY
            inversedBy: delivery
            joinColumns:
                order_id:
                    referencedColumnName: id
        syliusOrder:
            targetEntity: Sylius\Component\Order\Model\OrderInterface
            joinColumns:
                sylius_order_id:
                    referencedColumnName: id
    oneToMany:
        events:
            targetEntity: AppBundle\Entity\DeliveryEvent
            fetch: LAZY
            mappedBy: delivery
            orderBy:
                createdAt: ASC
    entityListeners:
        AppBundle\Entity\Listener\DeliveryListener:
            prePersist:
                - prePersist
            postPersist:
                - postPersist
