AppBundle\Entity\DeliveryOrderItem:
    type: entity
    table: delivery_order_item
    id:
        orderItem:
            associationKey: true
        delivery:
            associationKey: true
    manyToOne:
        orderItem:
            targetEntity: Sylius\Component\Order\Model\OrderItem
            fetch: LAZY
            mappedBy: null
            joinColumns:
                order_item_id:
                    referencedColumnName: id
            orphanRemoval: false
        delivery:
            targetEntity: AppBundle\Entity\Delivery
            fetch: LAZY
            mappedBy: null
            joinColumns:
                delivery_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
