AppBundle\Entity\Delivery:
    type: entity
    table: delivery
    repositoryClass: AppBundle\Entity\DeliveryRepository
    fields:
        weight:
            type: integer
            nullable: true
        vehicle:
            type: string
            nullable: true
    oneToOne:
        order:
            targetEntity: Sylius\Component\Order\Model\OrderInterface
            inversedBy: delivery
            joinColumns:
                order_id:
                    referencedColumnName: id
    manyToOne:
        store:
            targetEntity: AppBundle\Entity\Store
            inversedBy: deliveries
            joinColumn:
                store_id:
                    referencedColumnName: id
                    nullable: true
