AppBundle\Entity\Invoice:
    type: entity
    table: invoice
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: IDENTITY
    fields:
        number:
            type: string
        orderNumber:
            type: string
        issuedAt:
            type: datetime
            column: issued_at
            gedmo:
                timestampable:
                    on: create
        total:
            type: integer
    oneToMany:
        lineItems:
            targetEntity: AppBundle\Entity\Invoice\LineItem
            mappedBy: invoice
            cascade:
                - all
        footerItems:
            targetEntity: AppBundle\Entity\Invoice\FooterItem
            mappedBy: invoice
            cascade:
                - all
    manyToOne:
        emitter:
            targetEntity: AppBundle\Entity\Invoice\Stakeholder
            joinColumn:
                emitter_id:
                    referencedColumnName: id
            cascade:
                - all
        receiver:
            targetEntity: AppBundle\Entity\Invoice\Stakeholder
            joinColumn:
                receiver_id:
                    referencedColumnName: id
            cascade:
                - all
        order:
            targetEntity: Sylius\Component\Order\Model\OrderInterface
            joinColumn:
                order_id:
                    referencedColumnName: id
            cascade:
                - all
