AppBundle\Entity\Menu\MenuItem:
    type: entity
    table: menu_item
    gedmo:
        soft_deleteable:
            field_name: deletedAt
            time_aware: false
    fields:
        deletedAt:
            type: datetime
            nullable: true
            column: deleted_at
        isAvailable:
            type: boolean
            options:
                default: true
            column: is_available
        price:
            type: float
            nullable: true
        description:
            type: string
            nullable: true
        name:
            type: string
            nullable: true
        position:
            type: integer
            nullable: true
    manyToOne:
        section:
            targetEntity: AppBundle\Entity\Menu\MenuSection
            cascade:
                - all
            fetch: LAZY
            inversedBy: items
            joinColumns:
                parent_id:
                    referencedColumnName: id
    oneToMany:
        modifiers:
            targetEntity: AppBundle\Entity\Menu\MenuItemModifier
            cascade:
                - all
            fetch: LAZY
            mappedBy: menuItem
    entityListeners:
        AppBundle\Entity\Listener\MenuItemListener:
            postPersist:
                - postPersist
