AppBundle\Entity\Notification:
    type: entity
    table: notification
    repositoryClass: AppBundle\Entity\NotificationRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: IDENTITY
    fields:
        message:
            type: text
        routeName:
            type: string
            nullable: true
            column: route_name
        routeParameters:
            type: json_array
            nullable: true
            column: route_parameters
        read:
            column: is_read
            type: boolean
        createdAt:
            type: datetime
            column: created_at
            gedmo:
                timestampable:
                    on: create
    manyToOne:
        user:
            targetEntity: AppBundle\Entity\ApiUser
            joinColumns:
                user_id:
                    referencedColumnName: id
                    nullable: false
