AppBundle\Entity\OrderItem:
    type: entity
    table: order_item
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: IDENTITY
    fields:
        quantity:
            type: integer
        name:
            type: string
            nullable: true
        price:
            type: float
            nullable: true
    manyToOne:
        menuItem:
            targetEntity: AppBundle\Entity\Menu\MenuItem
            cascade:
                - persist
            fetch: LAZY
            joinColumns:
                menu_item_id:
                    referencedColumnName: id
        order:
            targetEntity: AppBundle\Entity\Order
            cascade:
                - persist
            fetch: LAZY
            inversedBy: orderedItem
            joinColumns:
                order_id:
                    referencedColumnName: id
                    nullable: false
    oneToMany:
        modifiers:
            targetEntity: AppBundle\Entity\OrderItemModifier
            cascade:
                - all
            fetch: LAZY
            mappedBy: orderItem
    entityListeners:
        AppBundle\Entity\Listener\OrderItemListener:
            prePersist:
                - prePersist
