AppBundle\Entity\StripeParams:
    type: entity
    table: stripe_params
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: SEQUENCE
    fields:
        userId:
            type: string
            column: user_id
