AppBundle\Entity\StripeTransfer:
    type: entity
    table: stripe_transfer
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: IDENTITY
    fields:
        transfer:
            type: string
            nullable: true
        transferGroup:
            type: string
            nullable: true
        currencyCode:
            type: string
            length: 3
            column: currency_code
        amount:
            type: integer
        state:
            type: string
        details:
            type: json_array
        createdAt:
            type: datetime
            column: created_at
            gedmo:
                timestampable:
                    on: create
        updatedAt:
            type: datetime
            column: updated_at
            gedmo:
                timestampable:
                    on: update
    manyToOne:
        stripeAccount:
            targetEntity: AppBundle\Entity\StripeAccount
            inversedBy: transfers
            fetch: LAZY
            joinColumns:
                stripe_account_id:
                    referencedColumnName: id
                    nullable: false
    oneToOne:
        stripePayment:
            targetEntity: AppBundle\Entity\StripePayment
            cascade:
                - all
            fetch: LAZY
            joinColumns:
                stripe_payment_id:
                    referencedColumnName: id
