AppBundle\Entity\Sylius\ProductVariant:
    type: entity
    table: sylius_product_variant
    fields:
        price:
            type: integer
    manyToOne:
        taxCategory:
            targetEntity: Sylius\Component\Taxation\Model\TaxCategoryInterface
            joinColumns:
                tax_category_id:
                    referencedColumnName: id
                    nullable: false
