AppBundle\Entity\Sylius\ProductOptionValue:
    type: entity
    table: sylius_product_option_value
    fields:
        price:
            type: integer
            nullable: true
    manyToOne:
        taxCategory:
            targetEntity: Sylius\Component\Taxation\Model\TaxCategoryInterface
            joinColumns:
                tax_category_id:
                    referencedColumnName: id
                    nullable: true
