services:

  _defaults:
    autowire: true
    autoconfigure: true

  Twig_Extensions_Extension_Text:
    class: Twig_Extensions_Extension_Text
    tags:
      - { name: twig.extension }

  Twig_Extensions_Extension_Intl:
    class: Twig_Extensions_Extension_Intl
    tags:
      - { name: twig.extension }

  AppBundle\Twig\OrderStateResolver:
    arguments: [ '@sm.factory' ]
    public: false
    tags:
      - { name: twig.runtime }

  AppBundle\Twig\SyliusVariantResolver:
    arguments: [ '@sylius.product_variant_resolver.default' ]
    public: false
    tags:
      - { name: twig.runtime }

  AppBundle\Twig\SettingResolver:
    arguments: [ '@coopcycle.settings_manager' ]
    public: false
    tags:
      - { name: twig.runtime }

  AppBundle\Twig\PriceFormatResolver:
    arguments:
      - '@sylius.context.currency'
      - '@sylius.templating.helper.currency'
    public: false
    tags:
      - { name: twig.runtime }

  AppBundle\Twig\MaintenanceResolver:
    arguments:
      - '@snc_redis.default'
    public: false
    tags:
      - { name: twig.runtime }

  AppBundle\Twig\BannerResolver:
    arguments:
      - '@snc_redis.default'
    public: false
    tags:
      - { name: twig.runtime }

  AppBundle\Twig\StripeResolver:
    arguments:
      - '@coopcycle.settings_manager'
    public: false
    tags:
      - { name: twig.runtime }
