services:

  _defaults:
    autowire: true
    autoconfigure: true

  Twig_Extensions_Extension_Text:
    class: Twig_Extensions_Extension_Text
    tags:
      - { name: twig.extension }

  Twig_Extensions_Extension_Intl:
    class: Twig_Extensions_Extension_Intl
    tags:
      - { name: twig.extension }
