name: Build
on:
  push:
    branches:
      - master
jobs:
  BUILD_ASSETS:
    name: Build assets
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - run: npm install
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install python-swiftclient python-keystoneclient
      - name: Compile assets for production
        run: NODE_ENV=production node_modules/.bin/encore production
      - name: Upload assets to storage
        run: |
          mkdir $GITHUB_SHA
          tar czvf $GITHUB_SHA/assets.tgz -C web/build .
          swift upload assets $GITHUB_SHA/assets.tgz
        env:
          ST_AUTH_VERSION: ${{ secrets.ST_AUTH_VERSION }}
          OS_USERNAME: ${{ secrets.OS_USERNAME }}
          OS_PASSWORD: ${{ secrets.OS_PASSWORD }}
          OS_USER_DOMAIN_NAME: ${{ secrets.OS_USER_DOMAIN_NAME }}
          OS_PROJECT_DOMAIN_NAME: ${{ secrets.OS_PROJECT_DOMAIN_NAME }}
          OS_AUTH_URL: ${{ secrets.OS_AUTH_URL }}
          OS_TENANT_ID: ${{ secrets.OS_TENANT_ID }}
          OS_TENANT_NAME: ${{ secrets.OS_TENANT_NAME }}
          OS_REGION_NAME: ${{ secrets.OS_REGION_NAME }}
